version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  main:
    jobs:
      - build


jobs:
  build:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build Distro  
          command: |
                poetry build
                poetry install
      - run:
          name: Run Tests
          command: |
                  # pip3 install pytest pytest-cov
                  pytest --juint-xml=report/report.xml
      - store_test_results:
          path: report
      - store_artifacts:
          path: htmlcov
  