version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  main:
    jobs:
      - build


jobs:
  build:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build Distro  
          command: poetry build
      - run:
          name: Run Tests
          command: |
                  pip3 install pytest pytest-cov
                  cp -r dope3 tests/dope3
                  pytest --cov=dope3 --cov-report=html
      - store_artifacts:
          path: htmlcov
  